apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: poller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: poller
    spec:
      containers:
      - name: poller
        image: thiagoarrais/anonydog-poller
        env:
          - name: REDIS_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: anonydog-secrets
                key: redis_database_url
          - name: GITHUB_API_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: anonydog-secrets
                key: github_api_access_token