apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  # 3 Pods should exist at all times.
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: backend
    spec:
      containers:
      - name: rabbitmq
        # Run this image
        image: rabbitmq:3.6