kind: Service
apiVersion: v1
metadata:
  name: webhook
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: webhook
  type: LoadBalancer
